#  Exemplo 3.1

In [3]:
# import library, fit, and transform
from sklearn.preprocessing import StandardScaler
import numpy as np

In [4]:
X = np.array([[ 1000, 0.01, 300],
[ 1200, 0.06, 350],
[ 1500, 0.1, 320]])

## compute mean & std column-wise

In [5]:
scaler = StandardScaler().fit(X)

## transform using computed mean and std

In [6]:
X_scaled = scaler.transform(X)

In [7]:
print("X= ", X)
print("X_scaled= ", X_scaled)

X=  [[1.0e+03 1.0e-02 3.0e+02]
 [1.2e+03 6.0e-02 3.5e+02]
 [1.5e+03 1.0e-01 3.2e+02]]
X_scaled=  [[-1.13554995 -1.26750044 -1.13554995]
 [-0.16222142  0.09053575  1.29777137]
 [ 1.29777137  1.1769647  -0.16222142]]
